### ISSUE TITLE
Recomiendo eliminar esto de github y pensar bien en sus opciones de carrera.

### ISSUE THREAD

**Issue by Nojipiz** [iFelex/Aromathera#1]
https://github.com/iFelex/Aromathera/blob/93df32800f8d4669c7008b82089557b95e8f05b9/server/app.js#L19

Es en serio??? .__.

Hay muchas opciones de carrera hoy en dia, le recomiendo encarecidamente que piense en otra que no incluya programación ni lógica básica.
No se lo tome a mal, pero debería dejar el repo en privado porque da muchísima pena ajena.
:D

**Comment by iFelex** [comment]
No xd

**Comment by Nojipiz** [comment]
._.
